[profile.default]
src = "contracts"
optimizer = true
via_ir = false
solc = "0.8.17"
out = "out"
libs = ["node_modules", "lib"]
test = './test'
remappings = [
    "@chainlink/=node_modules/@chainlink/",
    "@eth-optimism/=node_modules/@eth-optimism/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "eth-gas-reporter/=node_modules/eth-gas-reporter/",
    "hardhat/=node_modules/hardhat/",
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config